hostonly="yes"
hostonly_mode="strict"
hostonly_cmdline="yes"

install_items+=" /etc/crypttab "
install_items+=" /usr/bin/fido2-token "
install_items+=" /usr/lib/udev/rules.d/60-fido-id.rules "
install_items+=" /usr/lib/udev/fido_id "
